### ISSUE TITLE
App crash on iOS while sharing content on Facebook

### ISSUE THREAD

**Issue by kashifg4171** [bhagyashreekhatri/flutter_social_content_share#1]
App is crashing while sharing content on facebook on iOS and also not working sharing content on others except shareoption.

**Comment by bhagyashreekhatri** [comment]
Can check your proper image link and also steps to integrate it..add all properties in info.plist.

**Comment by kashifg4171** [comment]
> Can check your proper image link and also steps to integrate it..add all properties in info.plist.

Thank you, In my case, I was using an invalid facebookAppID.
