### ISSUE TITLE
Mail Recipients are not Comming

### ISSUE THREAD

**Issue by shaadart** [bhagyashreekhatri/flutter_social_content_share#10]
Hey, @bhagyashreekhatri 🚁 
I am Finding Trouble in Getting Recipients when I am using Mail.

```
                                 FlutterSocialContentShare.shareOnEmail(
                                                  recipients: [
                                                    "projectmaxsinss@gmail.com"
                                                  ],
                                                  ccrecipients: [
                                                    "projectmaxsinss@gmail.com"
                                                  ],
                                                  subject:
                                                      "Subject appears here",
                                                  body: "Body appears here",
                                                  isHTML:
                                                      true); 
```

I have Tried, ccrecipients, recipients, etc. but nothing worked, Also Tried Re-installing the Application,

**Comment by bhagyashreekhatri** [comment]
@madd-project can u try this code 

`String result = await FlutterSocialContentShare.shareOnEmail(
        recipients: ["projectmaxsinss@gmail.com"],
        ccrecipients: ["projectmaxsinss@gmail.com"],
        subject: "Subject appears here",
        body: "Body appears here",
        isHTML: true);
    print(result);`

and share me the log of `print(result);`

**Comment by shaadart** [comment]
@bhagyashreekhatri  I am afraid, I cannot see anything inside my Console. 
Else it is opening my Gmail.

**Comment by bhagyashreekhatri** [comment]
[https://drive.google.com/file/d/1W_P639ZYwknHDt8mDR86O36UD-4tlzNP/view?usp=sharing](https://drive.google.com/file/d/1W_P639ZYwknHDt8mDR86O36UD-4tlzNP/view?usp=sharing)

@madd-project I have attached the video of the working sample of the above lines  of the code. You can see on tap of email button its opening the mail and u can see the recipients as well.

**Comment by shaadart** [comment]
Lemme Again try this, 
And Will notify you as soon as I get some Response.

Right? @bhagyashreekhatri

**Comment by tree1891** [comment]
same here.
@madd-project please check below.
https://stackoverflow.com/questions/9097080/intent-extra-email-not-populating-the-to-field
