### ISSUE TITLE
IOS issue.

### ISSUE THREAD

**Issue by jodymac** [bhagyashreekhatri/flutter_social_content_share#12]
Android works fine, IOS doesn't (simulator and device).  IOS can't find the appid from the the info.plist.  There is a thread from May about this issue with IOS, apparently the facebook sdk 9.1 works while 9.2 and 9.3 are not able to find the info from the info.plist.  I tried this plugin with 0.0.4 after failing in 1.0.0 with the same result.

From the flutter terminal running vscode on my mac os big sur.
FBSDKLog: fbauth2 is missing from your Info.plist under LSApplicationQueriesSchemes and is required.
FBSDKLog: FBSDKGraphRequestConnection cannot be started before Facebook SDK initialized.

fbauth2 is there, I've moved it to the top, removed the others, rewritten it by hand instead of copying and pasting.

From Xcode log...
2021-06-25 14:52:30.455858-0700 Runner[43787:484858] FBSDKLog: fbauth2 is missing from your Info.plist under LSApplicationQueriesSchemes and is required.
2021-06-25 14:52:30.457516-0700 Runner[43787:484858] FBSDKLog: FBSDKGraphRequestConnection cannot be started before Facebook SDK initialized.
2021-06-25 14:52:30.567971-0700 Runner[43787:484858] -canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
2021-06-25 14:52:30.568573-0700 Runner[43787:484858] -canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
2021-06-25 14:52:30.568779-0700 Runner[43787:484858] FBSDKLog: FBSDKGraphRequestConnection cannot be started before Facebook SDK initialized.
2021-06-25 14:52:30.569039-0700 Runner[43787:484858] FBSDKLog: FBSDKGraphRequestConnection cannot be started before Facebook SDK initialized.
2021-06-25 14:52:30.569666-0700 Runner[43787:484858] -canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
2021-06-25 14:52:30.575549-0700 Runner[43787:484858] FBSDKLog: FBSDKGraphRequestConnection cannot be started before Facebook SDK initialized.
2021-06-25 14:52:30.588167-0700 Runner[43787:484858] *** Terminating app due to uncaught exception 'InvalidOperationException', reason: 'App ID not found. Add a string value with your app ID for the key FacebookAppID to the Info.plist or call [FBSDKSettings setAppID:].'

Flutter Doctor - 
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale
    en-US)
    • Flutter version 2.2.2 at /Users/jody/flutter/flutter
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jody/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554
      • android-x86    • Android 10 (API 29) (emulator)
    • IPhone SE 1st (mobile)             • FC37959B-EF84-4539-8CD0-7E65F23EBD3A
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)                    • macos
      • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)                       • chrome
      • web-javascript • Google Chrome 91.0.4472.114

**Comment by jodymac** [comment]
the appid issue is the last line of the xcode log when it terminates the app.  The fbauth2 not found is in both.

I read so many things trying to find the root of the issue, that I lost the link I had where the discussion was talking about the facebook sdk in ios not reading the info.plist values in the lastest builds.

**Comment by bhagyashreekhatri** [comment]
you need to add all these in info.plist 

`<key>LSApplicationQueriesSchemes</key>
    <array>
        <string>fbapi</string>
        <string>fbauth</string>
        <string>fbauth2</string>
        <string>fbshareextension</string>
        <string>fbapi20130214</string>
        <string>fbapi20130410</string>
        <string>fbapi20130702</string>
        <string>fbapi20131010</string>
        <string>fbapi20131219</string>
        <string>fbapi20140410</string>
        <string>fbapi20140116</string>
        <string>fbapi20150313</string>
        <string>fbapi20150629</string>
        <string>instagram</string>
        <string>instagram-stories</string>
        <string>whatsapp</string>
    </array>
  
  <key>NSPhotoLibraryAddUsageDescription</key>
    <string>Allow $(PRODUCT_NAME) access to your photo library to upload your profile picture?</string>
    <key>NSPhotoLibraryUsageDescription</key>
    <string>Allow $(PRODUCT_NAME) access to your photo library to upload your profile picture?</string>

  <key>FacebookAppID</key>
<string>xxxxxxxxxxxxxxx</string>

<key>FacebookDisplayName</key>
    <string>My App</string>
  `

**Comment by jodymac** [comment]
I had all that, however, as you closed this, I was testing the latest version of Xcode which I just upgraded to today, it seems to have fixed the issue with it not reading the info plist data which solves my problem.
