### ISSUE TITLE
share local video to instagram stories

### ISSUE THREAD

**Issue by aytunch** [bhagyashreekhatri/flutter_social_content_share#16]
Currently sharing video to Instagram stories is not possible. Only images are allowed.
Is there a limitation for this?
People usually post videos as stories and I think this would be a very nice feature.
I tried this in iOS and not in Android

**Comment by ilyoungkim** [comment]
I'm also curious about the answer to this question.
and with URL link.

**Comment by aytunch** [comment]
https://developers.facebook.com/docs/instagram/sharing-to-stories
facebook tells above to use these constants for sharing a video to stories.
@bhagyashreekhatri do you think you can implement a new `shareVideoToInstagramStories` function?

`instagram-stories://share?source_application=com.my.app`
`com.instagram.sharedSticker.backgroundVideo`

**Comment by bhagyashreekhatri** [comment]
No scope at the moment to implement this

**Comment by aytunch** [comment]
@ilyoungkim I implemented this just for iOS since we needed it at our company.
you can use it with this plugin:
https://pub.dev/packages/instagram_video_story_share
