### ISSUE TITLE
Ios exception 

### ISSUE THREAD

**Issue by ghost** [bhagyashreekhatri/flutter_social_content_share#17]
I tried to share image from file with instagram it works on android but on Ios I get this error :
nil host used in call to allowsSpecificHTTPSCertificateForHost
nil host used in call to allowsAnyHTTPSCertificateForHost:
NSURLConnection finished with error - code -1002

**Comment by bhagyashreekhatri** [comment]
Does your info.plist contains 

`<key>NSAppTransportSecurity</key>
<dict>
    <key>NSExceptionDomains</key>
    <dict>
        <key>localhost</key>
        <dict>
            <key>NSExceptionAllowsInsecureHTTPLoads</key>
            <true/>
        </dict>
    </dict>
</dict>`

`<key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    </dict>`

**Comment by ghost** [comment]
I add it like this but still the same error

`<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSAllowsArbitraryLoadsForMedia</key>
		<true/>
		<key>NSAllowsArbitraryLoadsInWebContent</key>
		<true/>
	</dict>
	<key>NSAppTransportSecurity</key>
	 <dict>
	 <key>NSExceptionDomains</key>
	  <dict>
	  <key>localhost</key>
	   <dict>
	   <key>NSExceptionAllowsInsecureHTTPLoads</key>
	   <true/>
	   </dict>
	    </dict>
	     </dict>`
