### ISSUE TITLE
On android 11 facebook share always open in web view no matter whether facebook app is installed or not. 

### ISSUE THREAD

**Issue by dhanrajVerma** [bhagyashreekhatri/flutter_social_content_share#19]
On android version <11 facebook share woks as expected. But on android 11 facebook share is always opening in popup webview window no matter whether facebook app is installed or not.
I am using flutter_social_content_share: ^1.0.1 
If you guys need more information please let me know

**Comment by bhagyashreekhatri** [comment]
This could be device issue. You need the check the device settings and make sure to enable the option of opening in the app instead of web.
