### ISSUE TITLE
problem with sharing on instagram in ios device.

### ISSUE THREAD

**Issue by dhanrajVerma** [bhagyashreekhatri/flutter_social_content_share#2]
case: When instagram app is not there in ios device (iPhone XR)
When I call below api I get the url which I passed to it. But in android I get proper message i.e. 'Instagram app is not installed on your device'
`FlutterSocialContentShare.share(
        type: ShareType.instagramWithImageUrl,
        imageUrl:
            "https://post.healthline.com/wp-content/uploads/2020/09/healthy-eating-ingredients-732x549-thumbnail-732x549.jpg");`
            I think problem is in line no 37 of  this [image.](https://www.dropbox.com/s/1orvy3e97z3m3wt/Screenshot%202021-01-04%20at%2010.14.38%20AM.png?dl=0)

**Comment by bhagyashreekhatri** [comment]
Hie,

I have fixed this issue and push the new version as well (https://pub.dev/packages/flutter_social_content_share/versions/0.0.4).
