### ISSUE TITLE
No such module 'FBSDKShareKit'

### ISSUE THREAD

**Issue by dhanucm** [bhagyashreekhatri/flutter_social_content_share#24]
I tried with old versions with 1.0.0 and 0.0.4. But still the same issue.

`flutter_social_content_share-0.0.4/ios/Classes/SwiftFlutterSocialContentSharePlugin.swift:91:31: error: 'init()' is
    unavailable
                let shareDialog = ShareDialog()
                                  ^~~~~~~~~~~
    FBSDKShareKit.ShareDialog:4:12: note: 'init()' has been explicitly marked unavailable here
        public init()
`

**Comment by kaciula** [comment]
I'm seeing the same issue when building the app for ios. Is there a workaround available?

**Comment by osmaneser** [comment]
I am getting the same error is there any solution?

**Comment by mtan11** [comment]
There is any solution for this? I have the same issue :(

**Comment by bhagyashreekhatri** [comment]
@mtan11  @osmaneser  @kaciula  @dhanucm  I have fixed this issue in version 1.0.2. Can fetch the latest version.
