### ISSUE TITLE
ExceptionInInitializerError while implement facebook login

### ISSUE THREAD

**Issue by ShilpaVania** [bhagyashreekhatri/flutter_social_content_share#5]
`[ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.ExceptionInInitializerError
E/flutter (21326): 	at com.bhagya.flutter_social_content_share.FlutterSocialContentSharePlugin.shareToFacebook(FlutterSocialContentSharePlugin.java:243)
E/flutter (21326): 	at com.bhagya.flutter_social_content_share.FlutterSocialContentSharePlugin.onMethodCall(FlutterSocialContentSharePlugin.java:114)
E/flutter (21326): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (21326): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (21326): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (21326): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (21326): 	at android.os.MessageQueue.next(MessageQueue.java:343)
E/flutter (21326): 	at android.os.Looper.loop(Looper.java:188)
E/flutter (21326): 	at android.app.ActivityThread.main(ActivityThread.java:7582)
E/flutter (21326): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (21326): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter (21326): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
E/flutter (21326): Caused by: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
E/flutter (21326): 	at com.facebook.internal.Validate.sdkInitialized(Validate.java:144)
E/flutter (21326): 	at com.facebook.FacebookSdk.getCallbackRequestCodeOffset(FacebookSdk.java:990)
E/flutter (21326): 	at com.facebook.internal.CallbackManagerImpl$RequestCodeOffset.toRequestCode(CallbackManagerImpl.java:119)
E/flutter (21326): 	at com.facebook.share.widget.ShareDialog.<clinit>(ShareDialog.java:105)
E/flutter (21326): 	... 12 more
E/flutter (21326): 
F/flutter (21326): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)] Check failed: CheckException(env). 
F/libc    (21326): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 21326 (xample.dealmate), pid 21326 (xample.dealmate)`

**Comment by bhagyashreekhatri** [comment]
Facebook is working fine. You need to check all the configurations done correctly or not in .plist for ios and .xml for Android
