### ISSUE TITLE
No implementation found for Method share on channel

### ISSUE THREAD

**Issue by crushman1** [bhagyashreekhatri/flutter_social_content_share#6]
When i try to use 
`FlutterSocialContentShare.share(
                  type: ShareType.more,
                  url: "https://url.com",
                  quote: widget.txt);`
I get

`Unhandled Exception: MissingPluginException(No implementation found for method share on channel flutter_social_content_share)`

**Comment by bhagyashreekhatri** [comment]
ShareType.more is not yet implememted.
