### ISSUE TITLE
Facebook content

### ISSUE THREAD

**Issue by thecreativedg** [bhagyashreekhatri/flutter_social_content_share#8]
FlutterSocialContentShare.share(
        type: ShareType.facebookWithoutImage,
        url: "https://www.apple.com",
        **quote:** "captions");

Brother, is there solution to share **content** on facebook **not a quote,** because quote is limited with number of charachters. I cant share long text on facebook. Thnx for wonderfull work

**Comment by bhagyashreekhatri** [comment]
Facebook allows only limited character to share. There is no alternative to share huge contents on facebook.
